config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :blogs

  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  root 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: blogs
#
#  id             :integer          not null, primary key
#  article        :text             not null
#  published_date :date
#  title          :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#
# Indexes
#
#  index_blogs_on_user_id  (user_id)
#

class Blog < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :user_id, inverse_of: :blogs

  scope :published, lambda {
    where("published_date <= ?", Time.zone.now)
      .where.not(published_date: nil)
  }

  def published?
    return false if published_date.blank?

    published_date <= Time.zone.now
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  display_name    :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  role            :integer          default("author"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  has_many :blogs, dependent: :destroy

  validates :display_name, presence: true
  validates :email, presence: true, email_format: true, uniqueness: true
  validates :password_confirmation, presence: true, if: ->(m) { m.password.present? }
  validates :role, presence: true

  enum role: {
    author: 0,
    admin: 2
  }

  def acts_as_admin?
    admin?
  end

  def acts_as_author?
    admin? || author?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index; end

  private

    def current_user
      return nil if session[:user_id].blank?

      @current_user ||= User.find_by(id: session[:user_id])
    end
    helper_method :current_user

    def user_not_authorized
      flash.now[:error] = "You are not authorized to perform this action."

      redirect_to(request.referer || root_path)
    end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  def index
    @blogs = policy_scope Blog.all
  end

  def show; end

  def new
    @blog = Blog.new
    authorize @blog
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    authorize @blog

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find(params[:id])
      authorize @blog
    end

    def blog_params
      params.require(:blog).permit(policy(Blog).permitted_attributes)
    end
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/MethodLength
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  skip_after_action :verify_authorized, :verify_policy_scoped

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = MicroBloggerWebSchema.execute(query, variables: variables, context: context,
                                                  operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end

  private

    # Handle variables in form data, JSON body, or a blank value
    def prepare_variables(variables_param)
      case variables_param
      when String
        if variables_param.present?
          JSON.parse(variables_param) || {}
        else
          {}
        end
      when Hash
        variables_param
      when ActionController::Parameters
        variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
      when nil
        {}
      else
        raise ArgumentError, "Unexpected parameter: #{variables_param}"
      end
    end

    def handle_error_in_development(error)
      logger.error error.message
      logger.error error.backtrace.join("\n")

      render json: { errors: [{ message: error.message, backtrace: error.backtrace }], data: {} },
             status: :internal_server_error
    end
end
# rubocop:enable Metrics/MethodLength

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_after_action :verify_authorized

  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in."
    else
      flash.now[:alert] = "Email or password is invalid."
      render "new"
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = policy_scope User.all
  end

  def show; end

  def new
    @user = User.new
    authorize @user
  end

  def edit; end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    def user_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :title
    = f.text_field :title

  .form-group
    = f.label :article
    = f.text_area :article, {rows: 10}

  .form-group
    = f.label :published_date
    = f.date_field :published_date

  .form-group
    = f.submit

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Back', blogs_path, {class: 'btn-tertiary'}

app/views/blogs/index.html.haml
%h1 Articles

- if policy(Blog).new?
  = link_to 'New Article', new_blog_path

- @blogs.each do |blog|
  %section.blog-entry
    %h2
      = link_to blog.title, blog
    %p= blog.article
    .author-tag
      = blog.author.display_name
      - unless blog.published_date.blank?
        \ -
        = l(blog.published_date)
      - if policy(blog).edit?
        \ -
        = link_to 'edit', edit_blog_url(blog)

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%h1= @blog.title

%p= @blog.article

%p
  Published date:
  - unless @blog.published_date.blank?
    = l(@blog.published_date)

%p
  \-
  = @blog.author.display_name

- if policy(@blog).edit?
  = link_to 'Edit', edit_blog_path(@blog)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag

    %title MicroBloggerWeb

    %link{href: "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body.blogger-container
    %header.blogger-header

    %main.blogger-main
      = render partial: 'shared/flash'
      = yield

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  .flash{class: "flash-#{key}"}
    = value

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :display_name
    = f.text_field :display_name

  .form-group
    = f.label :email
    = f.text_field :email

  - if current_user.acts_as_admin?
    .form-group
      = f.label :role
      = f.select :role, nil do
        = options_for_select User.roles.collect{ |s| [s[0].titlecase, s[0]]} , user&.role

  .form-group
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Users

- if policy(User).create?
  = link_to 'Create User', new_user_path

%table.full-table
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.display_name, edit_user_path(user)
        %td= user.email
        %td= user.role
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p= @user.display_name
%p= @user.email
%p= @user.role
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path